# Generated by Django 5.2 on 2025-08-14 05:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entries', '0003_alter_entry_options_entry_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='What do you need to remember?', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Additional details about this reminder')),
                ('date', models.DateField(help_text='When is this event/deadline?')),
                ('time', models.TimeField(blank=True, help_text='What time? (optional)', null=True)),
                ('category', models.CharField(choices=[('personal', '👤 Personal'), ('work', '💼 Work'), ('health', '🏥 Health'), ('social', '👥 Social'), ('birthday', '🎂 Birthday'), ('appointment', '📅 Appointment'), ('deadline', '⏰ Deadline'), ('event', '🎉 Event'), ('travel', '✈️ Travel'), ('other', '📝 Other')], default='personal', max_length=20)),
                ('priority', models.CharField(choices=[('low', '🟢 Low'), ('medium', '🟡 Medium'), ('high', '🔴 High'), ('urgent', '🆘 Urgent')], default='medium', max_length=10)),
                ('alert_preference', models.CharField(choices=[('none', 'No alerts'), ('day_of', 'Day of event'), ('1_day', '1 day before'), ('3_days', '3 days before'), ('1_week', '1 week before'), ('custom', 'Custom alerts')], default='1_day', max_length=10)),
                ('location', models.CharField(blank=True, help_text='Where is this happening? (optional)', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False, help_text='Mark as done')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
                ('related_entry', models.ForeignKey(blank=True, help_text='Link to diary entry about this event', null=True, on_delete=django.db.models.deletion.SET_NULL, to='entries.entry')),
            ],
            options={
                'verbose_name_plural': 'reminders',
                'ordering': ['date', 'time', '-priority'],
            },
        ),
    ]
