# Generated by Django 5.2 on 2025-12-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Repeat this event?'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='recurrence_type',
            field=models.CharField(choices=[('none', 'Does not repeat'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='none', help_text='How often does this repeat?', max_length=10),
        ),
    ]
