# Generated by Django 5.2 on 2025-08-14 05:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_alter_entry_options_entry_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='When this entry was archived', null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archive old entries to improve performance'),
        ),
        migrations.AddField(
            model_name='entry',
            name='mood',
            field=models.CharField(blank=True, choices=[('happy', '😊 Happy'), ('sad', '😢 Sad'), ('excited', '🎉 Excited'), ('calm', '😌 Calm'), ('stressed', '😰 Stressed'), ('grateful', '🙏 Grateful'), ('reflective', '🤔 Reflective'), ('energetic', '⚡ Energetic'), ('peaceful', '☮️ Peaceful'), ('other', '📝 Other')], help_text='How were you feeling during this entry?', max_length=50),
        ),
        migrations.AddField(
            model_name='entry',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags for easy searching (e.g., travel, work, family)', max_length=500),
        ),
        migrations.AddField(
            model_name='entry',
            name='word_count',
            field=models.IntegerField(default=0, help_text='Automatically calculated word count'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['author', 'is_archived', 'date'], name='entries_ent_author__3267ac_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['author', 'mood'], name='entries_ent_author__77a21f_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['created_at'], name='entries_ent_created_823464_idx'),
        ),
    ]
