# Generated by Django 5.2 on 2025-08-10 10:39

import entries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional: Upload an image for your diary entry', null=True, upload_to=entries.models.user_directory_path),
        ),
    ]
