# Generated by Django 5.2 on 2025-08-11 05:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_entry_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-date', '-created_at'], 'verbose_name_plural': 'entries'},
        ),
        migrations.AddField(
            model_name='entry',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='The date this diary entry is for'),
        ),
    ]
