# Generated by Django 5.2 on 2025-12-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='description',
            field=models.CharField(blank=True, help_text='Short plan description', max_length=255),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='marketing_text',
            field=models.CharField(blank=True, help_text='Marketing tagline or highlight', max_length=255),
        ),
    ]
