name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.13]  # Match our local environment

    env:
      DJANGO_SETTINGS_MODULE: core.settings
      DEBUG: False

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Check Django installation
      run: |
        python -c "import django; print(f'Django version: {django.get_version()}')"
        python manage.py check
    
    - name: Run migrations
      run: |
        python manage.py migrate --verbosity=2
    
    - name: Run tests
      run: |
        python manage.py test --verbosity=2 --parallel
